### ISSUE TITLE
Add possibility to pass a logger to requireScopesMiddleware

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#111]
The [requireScopesMilldeware](https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L40) currently responds "silently" with a `403` (see [here](https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L140)) when a request doe not provide an access token with sufficient scopes. However, it would be good to be able to additionally log something to somehow document such requests.

Therefore it should be possible to pass a logger (meeting the [Logger type](https://github.com/zalando-incubator/authmosphere/blob/master/src/types/Logger.ts)) to `requireScopesMilldeware`. The logger should be passed to [validateScopes](https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L125) and log an error in case of ["rejecting" the request](https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L140).

The logger currently passed to the `requestScopesMiddleware` via the [precedenceOptions parameter](https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L46) can then be omitted.

**Comment by ISO50** [comment]
Closed by #126
