### ISSUE TITLE
Make handleOAuthRequestMiddleware configurable in case of rejection

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#120]
Currently, if `handleOAuthRequestMiddleware` fails to validate the token of a request then it automatically rejects the request, see https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L108 and https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L114

`rejectRequest` (https://github.com/zalando-incubator/authmosphere/blob/master/src/utils.ts#L125) (or better the behaviour of it), should be configurable since it is now quite intransparent how the flow works.

**Comment by bzums** [comment]
The least we should do here is to be able to pass a logger to `handleOAuthRequestMiddleware`. Both changes would not be breaking afaik. What do you think @ISO50 @Retro64 ?

**Comment by Retro64** [comment]
Is that related to #16 ?

**Comment by bzums** [comment]
TBD whether this will land in 2.0.0

**Comment by ISO50** [comment]
closed by #154
