### ISSUE TITLE
Improve error message/logging of requestAccessToken 

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#127]
The oauth server response when requesting a token contains valuable information about the source of an error, we ignore those information, see: https://github.com/zalando-incubator/authmosphere/blob/master/src/oauth-tooling.ts#L84

We should use the response data in case of error to provide more valuable error messages. Furthermore we should think about accepting an optional logger as additional parameter.

**Comment by bzums** [comment]
We should also think about logging on the levels `info` and `debug`, maybe have a look at https://github.com/zalando/tokens for inspiration.

**Comment by bzums** [comment]
The same thing (add logging and improve error handling) should be done for [getTokenInfo](https://github.com/zalando-incubator/authmosphere/blob/master/src/oauth-tooling.ts#L132) 

Regarding the error handling: imo we should think about defining a type for errors:

```ts
type Problem = {
  message: string, // some high-level error message
  error: string | object // additional/low-level information about the error, like status code etc.
}
```

This type could then basically be used where we have to reject a promise which is accessible from outside the lib, I think that would be the following places in code:

* https://github.com/zalando-incubator/authmosphere/blob/master/src/oauth-tooling.ts#L93
* https://github.com/zalando-incubator/authmosphere/blob/master/src/oauth-tooling.ts#L149

What do you think @ISO50 @Retro64 ?

**Comment by Retro64** [comment]
@bzums I like the idea, but we should consider one of the params to be an optional (on minor problems like "Scope not found" it might produce redundancy just for its own sake if both params are mandatory)

**Comment by Retro64** [comment]
Merged in Release Branch - therefore closed
