### ISSUE TITLE
Fix async test cases for express tooling

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#132]
Fix problem described in https://github.com/zalando-incubator/authmosphere/pull/130/files/a35013288e9e091795d870f92a7b84ffa329d061#diff-c0d33e3fef66f9e1990b28d8d4eaca04R73

**Comment by Retro64** [comment]
Should contain refactoring/unifying of tests

**Comment by ISO50** [comment]
closed by #143
