### ISSUE TITLE
Security vulnerability in dependency tree

### ISSUE THREAD

**Issue by hypescript** [zalando-incubator/authmosphere#137]
Just FYI, there is a minor security vulnerability detected in your dependency tree: https://nodesecurity.io/check/authmosphere

Casual search for 'body-parser' usage haven't produced any results, removing body-parser and @types/body-parser doesn't seem to affect tests and build process in any way.

**Comment by bzums** [comment]
Good spot! It actually looks like we do not use it.

**Comment by Retro64** [comment]
Before taking action: According to https://nodesecurity.io/check/authmosphere/2.0.0-beta the 2.0.0-beta already seem to be fine, therefore the fix seem to be already in the next release

**Comment by ISO50** [comment]
Let's remove this dependency and it's typings from 2.0.0 branch:
https://github.com/zalando-incubator/authmosphere/blob/authmosphere-2-0-0/package.json#L28

**Comment by Retro64** [comment]
tackled in release branch - therefore closed
