### ISSUE TITLE
Review OAuthConfig type

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#149]
Having a look at https://github.com/zalando-incubator/authmosphere/blob/authmosphere-2-0-0-b/src/types/OAuthConfig.ts, `scopes` is non-optional for all grants expect `PasswordCredentialsGrantConfig`, however, regarding the RFC, `scope` is optional for all grants:
* https://tools.ietf.org/html/rfc6749#page-24
* https://tools.ietf.org/html/rfc6749#page-37
* https://tools.ietf.org/html/rfc6749#page-40
* https://tools.ietf.org/html/rfc6749#section-6

  Furthermore, for the type `TokenCacheOAuthConfig` the property `scopes` should not even be optional since we get the scopes from [tokenConfig](https://github.com/zalando-incubator/authmosphere/blob/authmosphere-2-0-0-b/src/TokenCache.ts#L81)

**Comment by Retro64** [comment]
Closed as merged in Release Branch
