### ISSUE TITLE
Improve documentation on OAuth configuration

### ISSUE THREAD

**Issue by jans510** [zalando-incubator/authmosphere#15]
In the documentation under oauthConfig, the config values should be entered using strings, for example 'PASSWORD_CREDENTIALS_GRANT' for grant type. Expected from the lib are not strings but constants, like PASSWORD_CREDENTIALS_GRANT = 'password'. So in order to enter a working configuration, the constant have to be entered, or a 'password' string. There should be a description on how to import and use the constants.

**Comment by bzums** [comment]
Addition to the documentation topic in general: evaluate http://typedoc.org/

**Comment by ISO50** [comment]
@jans510 could you provide a PR for this?
