### ISSUE TITLE
Migration Guide Draft

### ISSUE THREAD

**Issue by ISO50** [zalando-incubator/authmosphere#155]
### General changes

* All exported functions got support for a custom Logger. Any logger need to statisfy the Logger(TODO make a link, reference sourcefile) interface. Providing a logger is optional.
  * If your logging framework does not satisfy the interface, you need to wrap it somehow (provide example here?)
* To keep arguments lists short, we introduced `option` objects as parameter to group a number of (mostly) optional parameters.

**Comment by bzums** [comment]
Suggestion: the migration guide should only contain breaking changes and a small explanation how to apply them to get everything going again. Other changes should go into the Changelog (like additional loggers etc.). What do you think @ISO50 @Retro64 ?
