### ISSUE TITLE
getTokenInfo should allow to customize type Token

### ISSUE THREAD

**Issue by ISO50** [zalando-incubator/authmosphere#159]
```ts

.then((data) => getTokenInfo(oAuthConfig.tokeninfoEndpoint, data.access_token))
  .then((token: Token<{ uid: string }>/) => 
```

**Comment by ISO50** [comment]
As test: 
Promise.resolve({ tokeninfoEndpoint: '', access_token:''})
    .then(({ tokeninfoEndpoint, access_token }) => getTokenInfo<{ uid: string }>(tokeninfoEndpoint, access_token))
    .then((token: Token<{ uid: string }>) => token.uid)

**Comment by Retro64** [comment]
Merged in release branch - therefore closed
