### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#193]
Collect all issues we find in the final review of the documentation:

* https://github.com/zalando-incubator/authmosphere/blob/master/CHANGELOG.md#mocktokeninfoendpoint should not be under headline "New functionality to test OAuth behavior in case of error" but under "mockTokenInfoEndpoint" analogue to https://github.com/zalando-incubator/authmosphere/blob/master/CHANGELOG.md#mockaccesstokenendpoint-respects-scopes-property
* from readme: "It's implemented in TypeScript which improves the development experience via implicit documentation with types, first-class IDE support and provides mock tooling for local development." The mock tooling stuff should go in its own sentence
* https://github.com/zalando-incubator/authmosphere#cache-and-request-tokens should imo rather be called "Request and cache tokens"

**Comment by Retro64** [comment]
Closed as merged in #194
