### ISSUE TITLE
Update dependencies to get rid of security vulnerability

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#212]
See https://github.com/zalando-incubator/authmosphere/network/dependencies

**Comment by Retro64** [comment]
Never versions are not available yet. Just dev dependencies are involved.

Coveralls is already working on a fix: https://github.com/nickmerwin/node-coveralls/issues/188
NSP not yet https://github.com/nodesecurity/nsp/issues/250

We should consider to get rid of nsp, when the npm6 audit function is in place
