### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by ISO50** [zalando-incubator/authmosphere#57]
* [x] ~~Find name~~ (auth-mosphere)
* [x] Update readme
* [x] Update packages.json
* [x] push new version
* [x] Restart versioning at 1.0.0 #92

**Comment by bzums** [comment]
I would suggest "authmosphere"but i am also fine with the "dashed" version :)

And one additional task:
* [ ] rename repo

**Comment by Retro64** [comment]
i like the non-dashed version better either
