### ISSUE TITLE
HOWTO - Protect express endpoints with oAuth 

### ISSUE THREAD

**Issue by ISO50** [zalando-incubator/authmosphere#59]
Explain how to use the tooling to protect endpoints with oAuth scopes.

**Comment by bzums** [comment]
@ISO50 This is not necessarily an os blocker, is it?

**Comment by ISO50** [comment]
Documention consolidation was moved to a later milestone. So remove 'OS Blocker'.

**Comment by bzums** [comment]
Will be tackled in the documentation rewrite done with #46
