### ISSUE TITLE
Support explicitly passing credentials in OAuthConfig

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#60]
Currently you can only pass (user or client) credentials implicitly via the `credentialsDir` option in the [OAuthConfig type](https://github.com/zalando-incubator/authmosphere/blob/master/src/types/OAuthConfig.ts#L1). However it may be necessary sometimes to pass such information explicitly via a string. Furthermore, not for all grant types both information are mandatory.

This ticket may be related to #110 depending on the concrete solution.

See the current validation of OAuthConfig: https://github.com/zalando-incubator/authmosphere/blob/master/src/oauth-tooling.ts#L185 resp. https://github.com/zalando-incubator/authmosphere/blob/master/src/utils.ts#L143
See the current solution of reading in the credentials: https://github.com/zalando-incubator/authmosphere/blob/master/src/oauth-tooling.ts#L187

**Comment by bzums** [comment]
Blocked by #110

**Comment by Retro64** [comment]
Closed as merged in Release branch
