### ISSUE TITLE
Release authmosphere@1.0.0

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/authmosphere#92]
To be done:
 * [x] #91 
 * [x] #90
 * [x] #89
 * [x] #99  
 * [x] Release non-beta-version 
 * [x] deprecate `lib-oauth-tooling`

**Comment by bzums** [comment]
If stable version is released, deprecate `lib-oauth-tooling`: https://docs.npmjs.com/cli/deprecate

**Comment by Retro64** [comment]
Done with release and deprecation - therefore closed
