### ISSUE TITLE
Review compiler settings

### ISSUE THREAD

**Issue by Retro64** [zalando-incubator/authmosphere#99]
Are there any additional options that should be activated by default?

**Comment by Retro64** [comment]
@awaltert @ISO50 @bzums I would suggest:
```
    "strict":true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
```

**Comment by awaltert** [comment]
@Retro64 Looks good so far. If we activate `strictNullChecks` through `strict`, we will be faced with some errors relating to the type transformation for optional properties. Should this be addressed with this issue, or should we create a dedicated one?
